### PR TITLE
Use eventName provided by error

### PR DESCRIPTION
**Pull request by Aaronkala**
Part of https://github.com/getelevar/elevar-monorepo/issues/108

Use eventName provided by error instead of trying to get it from the dataLayer (often times this returns false).

If eventName is not provided in error try to get it from dataLayer. This is only so that the pixel is backwards compatible with older variable validation templates.

Add variable validation template version also to pixel to keep track of the versions people are using, so when everyone has migrated we can remove some of the functionality that is built for supporting older versions.

Also, bump version of template.

### CODE REVIEW

**Comment by Aaronkala** [comment]
Related to https://github.com/getelevar/gtm-monitoring-variables/pull/3

**Comment by Aaronkala** [comment]
@twslade Yeah we could so querying it would be easier

**Comment by twslade** [comment]
@Aaronkala we can revisit that. This looks good.

**Comment by Aaronkala** [comment]
@twslade If this is good I think we could merge this even if we don't have the new BQ column in place yet. It could then be added later on but the data would be null for some of the first errors with this info.

So we would get the better `event_name` fetching in place :)

**Comment by twslade** [comment]
@Aaronkala sounds good. Feel free to merge

**Pull request merged**
